version: '3.9'

services:
  loader:
    build:
      context: .
    container_name: loader
    restart: always
    ports:
      - "127.0.0.1:9000:9000"
    env_file:
      - .env
    environment:
      - DB_HOST=db
    networks:
      - movies-network

networks:
  movies-network:
    name: movies-network